OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "sk-36yCTsvz9hCLx52U59420cCc0e644127B5C9E28746468e61"

GLMModel:
  model_url: "https://api.xiaoai.plus/v1"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"